LabrWorkPr/CRUD_app/urls.py
from django.contrib import admin
from django.conf.urls import url 
from django.urls import path
from CRUD_app import views

app_name = 'CRUD_app'  

urlpatterns = [
    
    url(r'^socialNetworks$', views.socialNetworks_list, name='socialNetworks_list'), 
    url(r'^new$', views.socialNetworks_create, name='socialNetworks_new'),  
    url(r'^edit/(?P<pk>\d+)$', views.socialNetworks_update, name='socialNetworks_edit'),  
    url(r'^delete/(?P<pk>\d+)$', views.socialNetworks_delete, name='socialNetworks_delete'),   
    url(r'^$', views.home_page_cn), 
    url(r'^register/$', views.RegisterFormView.as_view()),
    url(r'^login/$', views.LoginFormView.as_view()),
    url(r'^logout/$', views.LogoutView.as_view()),
    
]

LabrWorkPr/LabrWorkPr/urls.py
from django.contrib import admin
from django.conf.urls import url 
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CRUD_app.urls')),
]

LabrWorkPr/CRUD_app/models.py
from django.db import models
from django.urls import reverse  
from django.contrib.auth.models import User  

# Create your models here.
class socialNetworks_types(models.Model):  
  
   title_cn = models.CharField(max_length=200)  
  
def __unicode__(self):  
  return self.title_cn 

def get_absolute_url(self):  
  return reverse('CRUD_app:socialNetworks_types_edit', kwargs={'pk': self.pk})
def __str__(self):
      return self.get_username()
def get_username(self):
      """Return the username for this User."""
      return getattr(self, 'title_cn')

class socialNetworks(models.Model):  
  
   user = models.ForeignKey(User, on_delete=models.CASCADE)  
   title = models.CharField(max_length=200)  
   url_cn = models.CharField(max_length=200)
   type_cn = models.ForeignKey(socialNetworks_types, on_delete=models.CASCADE)
  
   def __unicode__(self):  
     return self.title  
  
   def get_absolute_url(self):  
     return reverse('CRUD_app:socialNetworks_edit', kwargs={'pk': self.pk})

LabrWorkPr/CRUD_app/forms.py
from django import forms  
from .models import socialNetworks,socialNetworks_types  
   
   
class socialNetworksForm(forms.ModelForm):  
   
     class Meta:  
         model = socialNetworks  
         fields = ['user', 'title', 'url_cn', 'type_cn']  
         localized_fields = ('birth_date',)

class socialNetworksForm_types(forms.ModelForm):  
   
     class Meta:  
         model = socialNetworks_types  
         fields = ['title_cn']  

LabrWorkPr/CRUD_app/views.py
from django.shortcuts import render, get_object_or_404, redirect 
from django.contrib.auth.decorators import login_required  
from .forms import socialNetworksForm, socialNetworksForm_types
from CRUD_app.models import socialNetworks,socialNetworks_types 
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.views.generic.edit import FormView
from django.views.generic.base import View
from django.contrib.auth import login, logout
from django.http import HttpResponseRedirect

# Create your views here.
def home_page_cn(request):
    return render(request, 'Home_Page.html')  

class RegisterFormView(FormView):
    form_class = UserCreationForm

    # Ссылка, на которую будет перенаправляться пользователь в случае успешной регистрации.
    # В данном случае указана ссылка на страницу входа для зарегистрированных пользователей.
    success_url = "/login/"

    # Шаблон, который будет использоваться при отображении представления.
    template_name = "register.html"

    def form_valid(self, form):
        # Создаём пользователя, если данные в форму были введены корректно.
        form.save()

        # Вызываем метод базового класса
        return super(RegisterFormView, self).form_valid(form)

class LoginFormView(FormView):
    form_class = AuthenticationForm

    # Аналогично регистрации, только используем шаблон аутентификации.
    template_name = "register.html"

    # В случае успеха перенаправим на главную.
    success_url = "/"

    def form_valid(self, form):
        # Получаем объект пользователя на основе введённых в форму данных.
        self.user = form.get_user()

        # Выполняем аутентификацию пользователя.
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)

class LogoutView(View):
    def get(self, request):
        # Выполняем выход для пользователя, запросившего данное представление.
        logout(request)

        # После чего, перенаправляем пользователя на главную страницу.
        return HttpResponseRedirect("/")

@login_required  
def socialNetworks_list(request):  
     if request.user.is_superuser:  
         socialNetworkss = socialNetworks.objects.select_related().all(); 
     else:  
         socialNetworkss = socialNetworks.objects.filter(user=request.user)  
     return render(request, 'socialNetworks_list.html', {  
         'object_list': socialNetworkss  
     })  
  
  
@login_required  
def socialNetworks_create(request):  
     form = socialNetworksForm(request.POST or None)  
   
     if form.is_valid():  
         socialNetworkss = form.save(commit=False)  
         socialNetworkss.user = request.user  
         socialNetworkss.save()  
         return redirect('CRUD_app:socialNetworks_list')  
     return render(request, 'socialNetworks_form.html', {'form': form})  
  
  
@login_required  
def socialNetworks_update(request, pk):  
     if request.user.is_superuser:  
         socialNetworkss = get_object_or_404(socialNetworks, pk=pk)  
     else:  
         socialNetworkss = get_object_or_404(socialNetworks, pk=pk, user=request.user)  
     form = socialNetworksForm(request.POST or None, instance=socialNetworkss)  
     if form.is_valid():  
         form.save()  
         return redirect('CRUD_app:socialNetworks_list')  
     return render(request, 'socialNetworks_form.html', {'form': form})  
  
  
@login_required  
def socialNetworks_delete(request, pk):  
     if request.user.is_superuser:  
         socialNetworkss = get_object_or_404(socialNetworks, pk=pk)  
     else:  
         socialNetworkss = get_object_or_404(socialNetworks, pk=pk, user=request.user)  
     if request.method == 'POST':  
         socialNetworkss.delete()  
         return redirect('CRUD_app:socialNetworks_list')  
     return render(request, 'socialNetworks_delete.html', {'object': socialNetworks})

#socialNetworks_types

@login_required  
def socialNetworks_types_list(request):  
     if request.user.is_superuser:  
         socialNetworks = socialNetworks_types.objects.all()  
     else:  
         socialNetworks = socialNetworks_types.objects.filter(user=request.user)  
     return render(request, 'socialNetworks_list.html', {  
         'object_list': socialNetworks  
     })  
  
  
@login_required  
def socialNetworks_types_create(request):  
     form = socialNetworksForm_types(request.POST or None)  
   
     if form.is_valid():  
         socialNetworks = form.save(commit=False)  
         socialNetworks.user = request.user  
         socialNetworks.save()  
         return redirect('CRUD_app:socialNetworks_list')  
     return render(request, 'socialNetworks_form.html', {'form': form})  
  
  
@login_required  
def socialNetworks_types_update(request, pk):  
     if request.user.is_superuser:  
         socialNetworks = get_object_or_404(socialNetworks_types, pk=pk)  
     else:  
         socialNetworks = get_object_or_404(socialNetworks_types, pk=pk, user=request.user)  
     form = socialNetworksForm_types(request.POST or None, instance=socialNetworks)  
     if form.is_valid():  
         form.save()  
         return redirect('CRUD_app:socialNetworks_list')  
     return render(request, 'socialNetworks_form.html', {'form': form})  
  
  
@login_required  
def socialNetworks_types_delete(request, pk):  
     if request.user.is_superuser:  
         socialNetworks = get_object_or_404(socialNetworks_types, pk=pk)  
     else:  
         socialNetworks = get_object_or_404(socialNetworks_types, pk=pk, user=request.user)  
     if request.method == 'POST':  
         socialNetworks.delete()  
         return redirect('CRUD_app:socialNetworks_list')  
     return render(request, 'confirm_delete.html', {'object': socialNetworks})

LabrWorkPr/CRUD_app/templates/Home_Page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Starter Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/socialNetworks">CRUD-операции</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/admin">Админ панель</a>
      </li>
    </ul>
  </div>
</nav>

<main role="main" class="container">

  <div class="starter-template">
    <h1>Лабораторный проект</h1>
  </div>

</main><!-- /.container -->
</body>
</html>
 

LabrWorkPr/CRUD_app/templates/register.html
<!DOCTYPE html>
<html>
  <head>
    <title>Регистрация</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Зарегистрироваться</button>
    </form>
  </body>
</html>

LabrWorkPr/CRUD_app/templates/socialNetworks_delete.html
<h1>CRUD Function Based View Example</h1>  
 <form method="post">  
    {% csrf_token %}  
     Are you sure you want to delete "{{ object }}" ?  
     <input type="submit" value="Submit" />  
 </form>  

LabrWorkPr/CRUD_app/templates/socialNetworks_form.html
<h1>CRUD Function Based View Example</h1>  
 <form method="post">  
     {% csrf_token %}  
     {{ form.as_p }}  
     <input type="submit" value="Submit" />  
 </form>  

LabrWorkPr/CRUD_app/templates/socialNetworks_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Таблица Пользователей и их Социальных сетей</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <h1>CRUD Function Based View Example</h1>  
    <table class="table">
            <thead>
                <tr>
                    <th scope="col">NickName</th>
                    <th scope="col">Link</th>
                    <th scope="col">Social Network</th>
                    <th scope="col">EDIT</th>
                    <th scope="col">DELETE</th>
                </tr>
            </thead>
            <tbody>
                    
            {% for socialNetworks in object_list %}
                <tr>
                    <td scope="row">{{ socialNetworks.title }}</td>
                    <td scope="">{{  socialNetworks.url_cn }}</td>
                    <td scope="">{{  socialNetworks.type_cn.title_cn }}</td>
                    <td scope=""><a href="{% url 'CRUD_app:socialNetworks_edit' socialNetworks.id %}">edit</a> </td>
                    <td scope=""><a href="{% url 'CRUD_app:socialNetworks_delete' socialNetworks.id %}">delete</a></td>
               
                </tr>
            {% endfor %} 
        </tr>
    </tbody>
    </table>
   
 <a href="{% url 'CRUD_app:socialNetworks_new' %}">Add</a>  
</body>
</html>